"""
build_wiki_page.py
Wraps a Mermaid ERD file in a formatted Azure DevOps wiki page.

Usage:
    python build_wiki_page.py --mermaid docs/erd.mermaid --build-id 42 --out /tmp/wiki-page.md
"""
import argparse
from datetime import datetime, timezone


def build_content(mermaid_content: str, build_id: str) -> str:
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return f"""# ProductOrder — Entity Relationship Diagram

> Auto-generated by pipeline run **#{build_id}**. Last updated: **{timestamp}**

```mermaid
{mermaid_content.strip()}
```

---
*To regenerate, trigger the **Generate ERD** pipeline in Azure DevOps.*
"""


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--mermaid",  required=True, help="Path to .mermaid file")
    parser.add_argument("--build-id", required=True, help="ADO Build.BuildId")
    parser.add_argument("--out",      required=True, help="Output markdown file path")
    args = parser.parse_args()

    with open(args.mermaid, encoding="utf-8") as f:
        mermaid = f.read()

    content = build_content(mermaid, args.build_id)

    with open(args.out, "w", encoding="utf-8") as f:
        f.write(content)

    print(f"Wiki page content written to {args.out}")


if __name__ == "__main__":
    main()
